### ISSUE TITLE
shouldnt need phoenix and cowboy to run repeatex

### ISSUE THREAD

**Issue by warnerandy** [rcdilorenzo/repeatex#12]

**Comment by rcdilorenzo** [comment]
They are included as optional if you want the built-in router for a client live parsing a string.

**Comment by warnerandy** [comment]
when i include the repeatex repository in my application, mix tells me i need cowboy and phoenix.

**Comment by rcdilorenzo** [comment]
Okay, I'll take a look.

**Comment by rcdilorenzo** [comment]
I think I was referencing `Phoenix` in one of the modules without checking if it was loaded. I'll fix and you can let me know if that resolves the issue. I also plan to send up a version to hex.pm at some point.

**Comment by warnerandy** [comment]
Thanks I'll let you know

**Comment by rcdilorenzo** [comment]
@warnerandy, I've pushed the fix. Let me know if it works properly.
